#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import sys
import glob
import agent

def main():
    facts = {
        "tasks_total_count": 0,
        "tasks_delete_count": 0,
        "tasks_delete_older_count": 0,
        "tasks_inbox_count": 0,
        "tasks_inbox_and_delete_count": 0,
        "tasks_cron_enabled_count": 0,
    }
    count_tasks(facts)
    json.dump(facts, fp=sys.stdout)

def count_tasks(facts):
    for env_file in glob.iglob("imapsync/*.env"):
        task_env = agent.read_envfile(env_file)
        facts["tasks_total_count"] += 1
        if task_env.get("DELETE_REMOTE"):
            facts["tasks_delete_count"] += 1
        if 'older' in task_env.get("DELETE_REMOTE", ""):
            facts["tasks_delete_older_count"] += 1
        if task_env.get("FOLDER_INBOX"):
            facts["tasks_inbox_count"] += 1
        if task_env.get("FOLDER_INBOX") and task_env.get("DELETE_REMOTE"):
            facts["tasks_inbox_and_delete_count"] += 1
        if task_env.get("CRON"):
            facts["tasks_cron_enabled_count"] += 1

if __name__ == "__main__":
    main()
